INFO:handlers.dispatcher:Parsed html!
INFO:handlers.dispatcher:Created card list. Number of cards is 50
INFO:handlers.dispatcher:Wrote to db!
INFO:handlers.dispatcher:Parsed html!
INFO:handlers.dispatcher:Created card list. Number of cards is 50
INFO:handlers.dispatcher:Wrote to db!
INFO:handlers.dispatcher:Parsed html!
INFO:handlers.dispatcher:Created card list. Number of cards is 50
INFO:handlers.dispatcher:Wrote to db!
义但栺湡汤牥⹳楤灳瑡档牥债牡敳⁤瑨汭ਡ义但栺湡汤牥⹳楤灳瑡档牥䌺敲瑡摥挠牡⁤楬瑳‮畎扭牥漠⁦慣摲⁳獩㔠ਰ义但栺湡汤牥⹳楤灳瑡档牥场潲整琠⁯扤ਡ义但栺湡汤牥⹳楤灳瑡档牥䐺湯Ⅵ匠穩⁥景䐠㩂㔠‰潇湩⁧潴猠敬灥渠睯⸮‮空⹺⸮䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲慐獲摥栠浴Ⅼ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牃慥整⁤慣摲氠獩⹴丠浵敢⁲景挠牡獤椠⁳〵䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牗瑯⁥潴搠Ⅲ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲慐獲摥栠浴Ⅼ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牃慥整⁤慣摲氠獩⹴丠浵敢⁲景挠牡獤椠⁳〵䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牗瑯⁥潴搠Ⅲ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲慐獲摥栠浴Ⅼ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牃慥整⁤慣摲氠獩⹴丠浵敢⁲景挠牡獤椠⁳〵䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牗瑯⁥潴搠Ⅲ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲慐獲摥栠浴Ⅼ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牃慥整⁤慣摲氠獩⹴丠浵敢⁲景挠牡獤椠⁳〵䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牗瑯⁥潴搠Ⅲ䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠䴠捥慨䤠摮獵牴敩ੳ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偍㐭‵⁼牁瑣捩圠汯੦义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偍㐭‵⁼捓晡潦摬䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮卓⁇㠰簠䜠潨瑳䌠畲慳敤ੲ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䘠癩ⵥ敓敶⁎⁼楓癬牥儠慵瑲੺义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠䝕簠圠湩獧䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮潎慶簠䜠汩੡义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠偗簠倠偏䄠偗䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮坁⁐⁼潃瑲捩牥੡义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偓匭簠䌠牯整੸义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠偗簠䔠潸歳汥瑥湯䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠䌠湯灳物捡੹义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䜠潬正ㄭ‸⁼牗楡桴ੳ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䜠污汩䄠⁒⁼潒正瑥倠灯䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠䌠湯灳物捡੹义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩匠䝓〠‸⁼敆敶⁲牄慥੭义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩倠〲〰簠匠汩敶ੲ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠ⵋ㜴簠唠据慨瑲摥䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠䐠物捥楴敶䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮坁⁐⁼硅獯敫敬潴੮义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䜠潬正ㄭ‸⁼慃摮⁹灁汰੥义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偓匭簠䈠慬正䰠瑯獵䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮慇楬⁬剁簠嘠湡慤੬义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠ⵋ㜴簠䔠敭慲摬倠湩瑳楲数䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮汇捯⵫㠱簠䌠湡祤䄠灰敬䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮慇楬⁬剁簠䌠牨浯瑡捩䄠敢牲瑡潩੮义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䜠污汩䄠⁒⁼楓湧污䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠匠異湴歩䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮坁⁐⁼瑁敨楲ੳ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偓匭簠䌠牯整੸义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩倠〲〰簠匠汩敶ੲ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䐠獥牥⁴慅汧⁥⁼潃獮楰慲祣䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮坁⁐⁼楐⁴楖数ੲ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䘠癩ⵥ敓敶⁎⁼潃灰牥䜠污硡੹义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩唠偓匭簠䘠慬桳慢正䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮汇捯⵫㠱簠䌠敬牡倠汯浹牥䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠丠条੡义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䄠䝕簠䄠楲瑳捯慲ੴ义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䐠獥牥⁴慅汧⁥⁼牂湯敺䐠捥੯义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䴠䄴ⴱ⁓⁼慂楳楬歳䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮坁⁐⁼畓⁮湩䰠潥䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮䝓㔠㌵簠倠慨瑮浯䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敄敳瑲䔠条敬簠䈠潲穮⁥敄潣䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮㉐〵簠䘠慲歮楬੮义但栺湡汤牥⹳楤灳瑡档牥债潲散獳湩⁧歳湩䐠獥牥⁴慅汧⁥⁼楌桧⁴慒汩䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮婃㔷䄭瑵⁯⁼慔瑣捩瑡䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮㉐〵簠䴠敵瑲獯䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮卓⁇㠰簠䘠癥牥䐠敲浡䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮敎敧⁶⁼楌湯楦桳䤊䙎㩏慨摮敬獲搮獩慰捴敨㩲牐捯獥楳杮猠楫⁮㉍㤴簠丠扥汵⁡牃獵摡牥�INFO:root:Parsed html!
INFO:root:Created card list. Number of cards is 50
INFO:__main__:Dash is running on http://127.0.0.1:8050/

INFO:root:Parsed html!
INFO:root:Created card list. Number of cards is 50
INFO:__main__:Dash is running on http://127.0.0.1:8050/

INFO:__main__:Dash is running on http://127.0.0.1:8050/

INFO:root:Parsed html!
INFO:root:Created card list. Number of cards is 50
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug: * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/deps/react@16.v2_0_0m1647338568.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_0_0m1647338568.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_0_0m1647338568.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_0_0m1647338568.7.2.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:38] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug: * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:56] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:56] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:56] "[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:03:56] "[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:01] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:01] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:01] "[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:01] "[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1[0m" 304 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:35] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:36] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:37] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:38] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:39] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:39] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:40] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:40] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:41] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:42] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:43] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:44] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:45] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:46] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/yustas/PycharmProjects/TikTok_mastermind/dash_actions.py", line 16, in poll_result
    return dict(data=[dict(x=[0], y=[int(df['price'])], type="bar")],
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 18:04:47] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug: * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1[0m" 304 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:52] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:53] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:54] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:55] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:57] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:58] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:12:59] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:00] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:01] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:02] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:03] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:04] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:05] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:06] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:07] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:08] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:09] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:11] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:12] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:13] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:14] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:15] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:16] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:17] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:18] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:19] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:21] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:22] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:24] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:26] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:33] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_actions:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/Users/yustas/Library/Caches/pypoetry/virtualenvs/repl-python3-tiktokmastermind-FiszdxE2-py3.10/lib/python3.10/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: poll_result() takes 0 positional arguments but 1 was given
INFO:werkzeug:127.0.0.1 - - [15/Mar/2022 20:13:46] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:root:Parsed html!
INFO:root:Created card list. Number of cards is 50
INFO:root:Wrote to db!
INFO:root:Processing skin Glock-18 | Candy Apple
INFO:root:Processing skin Galil AR | Signal
INFO:root:Processing skin Five-SeveN | Boost Protocol
INFO:root:Processing skin MP9 | Goo
INFO:root:Processing skin P250 | Muertos
INFO:root:Processing skin AWP | Fever Dream
INFO:root:Processing skin P250 | Nevermore
INFO:root:Processing skin Glock-18 | Off World
INFO:root:Processing skin MP5-SD | Autumn Twilly
INFO:root:Processing skin Five-SeveN | Urban Hazard
INFO:root:Processing skin P250 | Franklin
INFO:root:Processing skin SG 553 | Tiger Moth
INFO:root:Processing skin Galil AR | Blue Titanium
INFO:root:Processing skin M4A1-S | Flashback
INFO:root:Processing skin SSG 08 | Parallax
INFO:root:Processing skin P250 | Inferno
INFO:root:Processing skin P250 | X-Ray
INFO:root:Processing skin MAC-10 | Lapis Gator
INFO:root:Processing skin CZ75-Auto | Yellow Jacket
INFO:root:Processing skin Desert Eagle | Bronze Deco
INFO:root:Processing skin SSG 08 | Fever Dream
INFO:root:Processing skin MAC-10 | Propaganda
INFO:root:Processing skin FAMAS | Survivor Z
INFO:root:Processing skin M4A1-S | Fizzy POP
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:root:Processing skin P250 | Ripple
INFO:root:Processing skin Glock-18 | Reactor
INFO:root:Processing skin AWP | Exoskeleton
INFO:root:Processing skin USP-S | Cyrex
INFO:root:Processing skin Desert Eagle | Directive
INFO:root:Processing skin Five-SeveN | Monkey Business
INFO:root:Processing skin Glock-18 | Catacombs
INFO:root:Processing skin R8 Revolver | Reboot
INFO:root:Processing skin M4A4 | X-Ray
INFO:root:Processing skin Desert Eagle | Night
INFO:root:Processing skin AK-47 | Blue Laminate
INFO:root:Processing skin MAC-10 | Disco Tech
INFO:root:Processing skin Glock-18 | Water Elemental
INFO:root:Processing skin FAMAS | ZX Spectron
INFO:root:Processing skin SSG 08 | Turbo Peek
INFO:root:Processing skin Desert Eagle | Night Heist
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:root:Processing skin MAC-10 | Disco Tech
INFO:root:Processing skin SCAR-20 | Grotto
INFO:root:Processing skin USP-S | Guardian
INFO:root:Processing skin SSG 08 | Abyss
INFO:root:Processing skin Galil AR | Rocket Pop
INFO:root:Processing skin AK-47 | Safari Mesh
INFO:root:Processing skin AWP | Pit Viper
INFO:root:Processing skin USP-S | Flashback
INFO:root:Processing skin Five-SeveN | Violent Daimyo
INFO:root:Processing skin USP-S | Cyrex
INFO:root:Done! Size of DB: 50 Going to sleep now... zzz...
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:root:Parsed html!
INFO:root:Created card list. Number of cards is 50
INFO:root:Wrote to db!
INFO:root:Processing skin P2000 | Imperial
INFO:root:Processing skin USP-S | Black Lotus
INFO:root:Processing skin P250 | X-Ray
INFO:root:Processing skin Tec-9 | Ice Cap
INFO:root:Processing skin Sawed-Off | Amber Fade
INFO:root:Processing skin USP-S | Torque
INFO:root:Processing skin AWP | Pit Viper
INFO:root:Processing skin CZ75-Auto | Crimson Web
INFO:root:Processing skin P250 | X-Ray
INFO:root:Processing skin Glock-18 | Candy Apple
INFO:root:Processing skin Galil AR | Signal
INFO:root:Processing skin Five-SeveN | Boost Protocol
INFO:root:Processing skin MP9 | Goo
INFO:root:Processing skin P250 | Muertos
INFO:root:Processing skin AWP | Fever Dream
INFO:root:Processing skin P250 | Nevermore
INFO:root:Processing skin Glock-18 | Off World
INFO:root:Processing skin MP5-SD | Autumn Twilly
INFO:root:Processing skin Five-SeveN | Urban Hazard
INFO:root:Processing skin P250 | Franklin
INFO:root:Processing skin SG 553 | Tiger Moth
INFO:root:Processing skin Galil AR | Blue Titanium
INFO:root:Processing skin M4A1-S | Flashback
INFO:root:Processing skin SSG 08 | Parallax
INFO:root:Processing skin P250 | Inferno
INFO:root:Processing skin P250 | X-Ray
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:root:Processing skin MAC-10 | Lapis Gator
INFO:root:Processing skin CZ75-Auto | Yellow Jacket
INFO:root:Processing skin Desert Eagle | Bronze Deco
INFO:root:Processing skin SSG 08 | Fever Dream
INFO:root:Processing skin MAC-10 | Propaganda
INFO:root:Processing skin FAMAS | Survivor Z
INFO:root:Processing skin M4A1-S | Fizzy POP
INFO:root:Processing skin P250 | Ripple
INFO:root:Processing skin Glock-18 | Reactor
INFO:root:Processing skin AWP | Exoskeleton
INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:dash_actions:Dash is running on http://127.0.0.1:8050/

INFO:__main__:Dash is running on http://127.0.0.1:8050/

